### PR TITLE
User profile page & coupons

### PR DESCRIPTION
**Pull request by msdeshmukh009**
- Added user profile page.
- Coupons in the cart.

coupons

user-profile

### CODE REVIEW

**Comment by RahulKuvlekar** [comment]
Everything looks good. Clean Code. Good to merge 👍🏻

**Review by preethasri — APPROVED** [review]
good to merge

**Review by kiranpratyush — APPROVED** [review]
CSS styling is uniform  nice and clean
good to go for me

**Review by Chakravarthi0 — APPROVED** [review]
clean code
good to merge

**Pull request merged**
